/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Model.Banco;
import Model.Cliente;

import Telas.TelaGerenciarBancos;
import bank.Serializar;
import bank.Servidor;
import bank.ServidorNotificacoes;

import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yurif
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private Boolean servidorAtivo = false;
    private Thread thread;
    private Thread thread2;
    private Servidor servidor;
    
    private ServidorNotificacoes servidorNotificacoes;
    
    private int usuarios = 0;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        bt_gerente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        statusServidorText = new javax.swing.JLabel();
        numeroClientes = new javax.swing.JLabel();
        numeroBancos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextLog = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        jButton2.setText("ATIVAR SERVIDOR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bt_gerente.setText("GERENCIAR BANCOS");
        bt_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gerenteActionPerformed(evt);
            }
        });

        jLabel1.setText("STATUS SERVIDOR:");

        statusServidorText.setText("Offline");

        numeroClientes.setText("NUMERO DE CONTAS:");

        numeroBancos.setText("NUMERO DE BANCOS:");

        jTextLog.setBackground(new java.awt.Color(0, 0, 0));
        jTextLog.setColumns(20);
        jTextLog.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        jTextLog.setForeground(new java.awt.Color(51, 255, 0));
        jTextLog.setRows(5);
        jTextLog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextLog.setSelectionColor(new java.awt.Color(0, 102, 51));
        jScrollPane1.setViewportView(jTextLog);

        jLabel5.setText("LOG");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bank");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusServidorText)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroBancos)
                            .addComponent(bt_gerente)
                            .addComponent(numeroClientes))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(bt_gerente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(statusServidorText)
                    .addComponent(numeroBancos))
                .addGap(18, 18, 18)
                .addComponent(numeroClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        if(!servidorAtivo){
            servidor = new Servidor(this);
            servidorNotificacoes = new ServidorNotificacoes(this);
            try{
                thread = new Thread(servidor);
                thread2 = new Thread(servidorNotificacoes);
                thread2.start();
                thread.start();
                servidorAtivo = true;
                jButton2.setText("DESATIVAR SERVIDOR");
                  
                statusServidorText.setText("Online");
                
                
            }catch (Exception e){
                 printar("Erro ao ativar servidor");
            }
            
        }else{
            
            try {
                servidor.fechar();
                servidorNotificacoes.fechar();
                thread.join();
                thread2.join();
               
                servidorAtivo = false;
                jButton2.setText("ATIVAR SERVIDOR");
                
                
                statusServidorText.setText("Offline");
            } catch (Exception e) {
                 printar("Erro ao desligar servidor");
            }
            
        }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bt_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gerenteActionPerformed
        TelaGerenciarBancos telaGerenciar = new TelaGerenciarBancos();
        telaGerenciar.setVisible(true);
        
        
    }//GEN-LAST:event_bt_gerenteActionPerformed
    
    
    public void printar(String add){
        String texto = jTextLog.getText();
        
        texto+=" > " +add+ "\n";
        
        jTextLog.setText(texto);
        
    }
    public void contarUsuarios(){
        
        ArrayList<Cliente> clientes = Serializar.listarClientes();
        
        if(clientes == null){
             numeroClientes.setText("NUMERO DE CLIENTES: 0" );
        }
            
        numeroClientes.setText("NUMERO DE CLIENTES: " + clientes.size());
         
    }
    
    public void contarBancos(){
        ArrayList<Banco> bancos = Serializar.listarBancos();
        
        if(bancos == null){
             numeroBancos.setText("NUMERO DE BANCOS: 0" );
        }
            
        numeroBancos.setText("NUMERO DE BANCOS: " + bancos.size());
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
                Banco banco = new Banco();
              
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_gerente;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextLog;
    private javax.swing.JLabel numeroBancos;
    private javax.swing.JLabel numeroClientes;
    private javax.swing.JLabel statusServidorText;
    // End of variables declaration//GEN-END:variables
}
